### ISSUE TITLE
Can't access (loop)

### ISSUE THREAD

**Issue by masiv1001** [tekgator/docker-mcmyadmin#12]
Problem: After installing I'm not able to access the admin panel, after the normal logs it loops on these lines of code
```
./MCMA2_Linux_x86_64 started.
************************************************************************ 
*                                                                      * 
* McMyAdmin started, access via http://localhost:8080                  * 
************************************************************************
Script finished, attaching to the McMyAdmin log now.
./MCMA2_Linux_x86_64 not running anymore, stop script to stop container!
Starting ./MCMA2_Linux_x86_64...
```

**Comment by tekgator** [comment]
Hi @masiv1001,

could you please post the hardware you are using. Please not that McMyAdmin will not run on ARM hardware.
If thats not the reason please paste your run command or your docker-compose entry.

**Comment by masiv1001** [comment]
I'm using a pc with and amd x64 processor, here is the docker.yml file -->
```
version: "3"
services:
  mcmyadmin:   
    image: tekgator/docker-mcmyadmin:latest
    container_name: mcmyadmin
    environment:
      PUID: 1000
      PGID: 1000
      EULA: 1
    volumes:
      - /run/media/[REDACTED]/containers/mcmyadmin:/data
    ports:
      - 8082:8080
      - 25565:25565
    stop_grace_period: 30s
    restart: unless-stopped
```

**Comment by tekgator** [comment]
I've tried quite a lot and can't get it to crash. Maybe a few more things to consider:

- Uid/Gid 1000/1000 does exist on the host?
- Is 1000/1000 the owner of /run/media/[REDACTED]/containers/mcmyadmin?
- Does 1000/1000 have Chmod 700  on /run/media/[REDACTED]/containers/mcmyadmin?

**Comment by kyle170** [comment]
I'm also suffering from this issue. I've also checked the 3 items in the post above.
```
  mcmyadmin:
    image: tekgator/docker-mcmyadmin:latest
    container_name: mcmyadmin
    environment:
      PUID: 1001
      PGID: 1001
      EULA: 1
    volumes:
      - /home/kyle/mcmyadmin:/data
    ports:
      - 8082:8080
      - 25565:25565
    stop_grace_period: 30s
    restart: unless-stopped
``` 

![Image](https://github.com/user-attachments/assets/5a7d979b-5f2c-44d3-8808-2519070bd2c9)

![Image](https://github.com/user-attachments/assets/c702c22c-72f7-4695-9c1f-5c3ab6d8e7df)


There was also this in the logs on the first-run... Maybe this gives some info
```
Native stacktrace:

	./MCMA2_Linux_x86_64() [0x60c99d]

	./MCMA2_Linux_x86_64() [0x44c1bf]

	/lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7b135b176d60]

	./MCMA2_Linux_x86_64() [0x53290f]

	./MCMA2_Linux_x86_64() [0x48d6be]

	./MCMA2_Linux_x86_64() [0x45601b]

	./MCMA2_Linux_x86_64() [0x40c109]

	./MCMA2_Linux_x86_64() [0x40b3ab]

	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7b135b161d0a]

	./MCMA2_Linux_x86_64() [0x40afb9]

Debug info from gdb:

=================================================================

Got a SIGSEGV while executing native code. This usually indicates

a fatal error in the mono runtime or one of the native libraries 

used by your application.

=================================================================

/app/app.sh: line 9:    30 Aborted                 (core dumped) ./MCMA2_Linux_x86_64 -nonotice -updateonly
```
